# Generated by Django 5.0.4 on 2024-04-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership', models.CharField(max_length=255)),
                ('number_of_appartment', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('category_appartment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='task.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('jshshir', models.BigIntegerField()),
                ('phone_number', models.CharField(max_length=255)),
                ('appartment', models.IntegerField()),
                ('appartment_type', models.CharField(max_length=255)),
                ('cadastr_number', models.CharField(max_length=255)),
                ('status_of_registration', models.CharField(max_length=255)),
                ('time_registered', models.DateTimeField()),
                ('address_of_passport', models.CharField(max_length=255)),
                ('category_appartment', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='task.house')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='task.region'),
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=255)),
                ('document_series', models.CharField(max_length=20)),
                ('document_number', models.IntegerField()),
                ('kinship', models.CharField(max_length=255)),
                ('jshshir', models.BigIntegerField()),
                ('phone_number', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('disability', models.CharField(max_length=255)),
                ('war_participant', models.BooleanField(default=False)),
                ('no_breadwinner', models.BooleanField(default=False)),
                ('lonely_old_man', models.BooleanField(default=False)),
                ('difficult_condition', models.BooleanField(default=False)),
                ('behind_war', models.BooleanField(default=False)),
                ('gone_for_along_time', models.BooleanField(default=False)),
                ('participant_of_AES', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='task.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='task.neighborhood')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='task.street'),
        ),
    ]
