# Generated by Django 5.0.4 on 2024-04-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='street',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='street',
            name='updated_at',
        ),
    ]
