# Generated by Django 5.0.4 on 2024-04-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_person_residential_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category_appartment',
        ),
    ]
