# Generated by Django 5.0.4 on 2024-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='jshshir',
            field=models.CharField(),
        ),
    ]
