# Generated by Django 5.0.4 on 2024-04-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_person_jshshir'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='task.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='task.neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='task.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='task.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='task.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='task.region'),
            preserve_default=False,
        ),
    ]
